name: Update Azure Service Tags

on:
  schedule:
    - cron: "0 7 * * *"  # Runs daily at 7 AM UTC
  workflow_dispatch:      # Allow manual runs

permissions:
  id-token: write         # Required for OIDC
  contents: write         # Needed if we commit changes to the repo

jobs:
  update-azure-service-tags:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Retrieve & Compare Azure Service Tags
        shell: pwsh
        run: |
          try {
            # 1) Get management token from Azure CLI
            $token = az account get-access-token `
              --resource https://management.azure.com `
              --query accessToken -o tsv

            if (-not $token) {
              Write-Error "No token retrieved from az account get-access-token."
              exit 1
            } 

            # 2) Build the REST call
            $subscriptionId = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            $location       = "westeurope"
            $apiVersion     = "2024-05-01"
            $uri = "https://management.azure.com/subscriptions/$subscriptionId/providers/Microsoft.Network/locations/$location/serviceTags?api-version=$apiVersion"

            Write-Host "Querying Azure Service Tags from $uri ..."
            $headers = @{
              "Authorization" = "Bearer $token"
              "Content-Type"  = "application/json"
            }

            [void]($response = Invoke-RestMethod -Uri $uri -Headers $headers -Method GET)
            if (-not $response.values) {
              Write-Error "Unexpected API response: $($response | ConvertTo-Json -Depth 10)"
              exit 1
            }

            # 3) Flatten results into a PowerShell list of objects
            $allTags = @{}
            foreach ($tag in $response.values) {
              $allTags[$tag.name] = @{
                Tag         = $tag.name
                Region      = $tag.properties.region
                IPAddresses = $tag.properties.addressPrefixes
              }
            }

            [void]($expandedList = foreach ($key in $allTags.Keys) {
              $tagEntry = $allTags[$key]
              foreach ($ip in $tagEntry.IPAddresses) {
                [PSCustomObject]@{
                  Tag       = $tagEntry.Tag
                  Region    = $tagEntry.Region
                  IPAddress = $ip
                }
              }
            })

            # 4) Sort by Tag, Region, IPAddress for stable ordering
            [void]($sortedList = $expandedList | Sort-Object -Property Tag, Region, IPAddress -Unique)

            # 5) Convert to CSV in memory
            $newContent = $sortedList | ConvertTo-Csv -NoTypeInformation | Out-String
            [void]$newContent

            # 6) Compare with existing file (cloud-ip-ranges/azure-service-tags.csv)
            $csvPath = "cloud-ip-ranges/azure-service-tags.csv"

            if (Test-Path $csvPath) {
                $oldContent = Get-Content $csvPath -Raw
                $oldContentNormalized = ($oldContent -replace "\r\n", "`n").Trim()
                $newContentNormalized = ($newContent -replace "\r\n", "`n").Trim()

                Write-Host "Old content line count: $($oldContentNormalized -split "`n").Count"
                Write-Host "New content line count: $($newContentNormalized -split "`n").Count"

                if ($oldContentNormalized -ne $newContentNormalized) {
                    Write-Host "Files differ. Replacing $csvPath with new content."
                    $newContent | Set-Content -Path $csvPath -NoNewline
                } else {
                    Write-Host "No changes detected. The repo file is already up-to-date."
                }
            } else {
                Write-Host "$csvPath does not exist. Creating a new file."
                $newContent | Set-Content -Path $csvPath -NoNewline
            }
          }
          catch {
            Write-Error "An error occurred: $_"
            exit 1
          }

      - name: Commit changes
        shell: pwsh
        run: |
          git config user.name "KustoKing[bot]"
          git config user.email "gianni@kustoking.com"

          $dateString = (Get-Date -Format "yyyyMMdd")
          $csvPath = "cloud-ip-ranges/azure-service-tags.csv"

          git add $csvPath
          git commit -m "ci: update azure service tags $dateString"
          git push
